version: '3'

services:
  nodejs:
    image: tiagoreichert/cloud-challenge-nodejs:1.0
    ports:
      - 3000:3000
    deploy:
       replicas: 1
  log_parser:
    image: tiagoreichert/cloud-challenge-logparser
    environment:
      - SERVICE_NAME=app_nodejs
      - SMTP_SERVER=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_TLS=True
      - SMTP_NAME=Cloud Challenge
      - SMTP_USERNAME=
      - SMTP_PASSWORD=
      - SMTP_RECIPIENT=
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock