version: '3'

services:
  nodejs:
    image: tiagoreichert/cloud-challenge-nodejs:1.0
    deploy:
       replicas: {NODEJS_REPLICAS}
  nginx:
    image: tiagoreichert/cloud-challenge-nginx
    depends_on:
      - nodejs
    ports:
      - 443:443
      - 80:80
    volumes:
      - nginx-logs:/var/log/nginx/
    environment:
      - NGINX_WORKERS={NGINX_WORKERS}
  logparser:
    image: tiagoreichert/cloud-challenge-logparser
    depends_on:
      - nginx
    environment:
      - SMTP_SERVER={SMTP_SERVER}
      - SMTP_PORT={SMTP_PORT}
      - SMTP_TLS={SMTP_TLS}
      - SMTP_NAME={SMTP_NAME}
      - SMTP_USERNAME={SMTP_USERNAME}
      - SMTP_PASSWORD={SMTP_PASSWORD}
      - SMTP_RECIPIENT={SMTP_RECIPIENT}
      - TZ=America/Sao_Paulo
      - CRON_MASK={CRON_MASK}
    volumes:
      - nginx-logs:/log/

volumes:
  nginx-logs:
